<?php

namespace rollun\test\promise\Entity;

use PHPUnit\Framework\TestCase;
use rollun\promise\Entity\Base;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-20 at 14:36:01.
 */
class BaseTest extends TestCase
{

    /**
     * @var Async
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Base;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testIsId()
    {
        $this->assertTrue(
                $this->object->isId('entity__1119864461_889811__579c843dd93ad1_08516192')
        );
        $this->assertFalse(
                $this->object->isId('queue__1119864461_889811__579c843dd93ad1_08516192')
        );
        $this->assertFalse(
                $this->object->isId('entity__1119864461_889811__579c843dd93ad1_085161')
        );
        $this->assertFalse(
                $this->object->isId('queue__1119864461_889811__579c843dd93ad1_A8516192')
        );
    }

    public function testGetPrefix()
    {
        $this->assertEquals(
                'entity', $this->object->getPrefix()
        );
    }

    public function dataProvider_ExtractId()
    {
        return array(
            [
                ' jkiuhs iuhis pi siuiughf]l;m74jn &568ihj983438h^&%  ',
                []
            ],
            [
                ' jkiuhs iuhis pi siu entity__1469864422_189511__579c84162e43e4_34952052 iughf]l;m74jn &568ihj983438h^&%  ',
                ['entity__1469864422_189511__579c84162e43e4_34952052']
            ],
            [
                ' jkiuhs iuhis pi s entity__2229864461_889811__579c843dd93ad1_08516192  AND entity__3339864461_889811__579c843dd93ad1_08516192',
                [
                    'entity__3339864461_889811__579c843dd93ad1_08516192',
                    'entity__2229864461_889811__579c843dd93ad1_08516192',
                ]
            ],
        );
    }

    /**
     *
     * @dataProvider dataProvider_ExtractId
     */
    public function testExtractId($val, $result)
    {
        $this->assertEquals(
                $result, $this->object->extractId($val)
        );
    }

}
