<?php

namespace rollun\test\promise\Entity;

use PHPUnit\Framework\TestCase;
use rollun\promise\Entity\Entity;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-20 at 14:36:01.
 */
class EntityTest extends TestCase
{

    /**
     * @var Async
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function test__isId()
    {
        $this->object = new Entity();
        $this->assertTrue(
                $this->object->isId($this->object->getId())
        );
    }

    public function test__getData()
    {
        $this->object = new Entity();
        $this->assertArrayHasKey(
                'id', $this->object->getData()
        );
    }

}
